workflows:
  HTT-Safety-Web-App-iOS:
    name: HTT Safety iOS
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: .  # Change to 'ios/' if Xcode project is in subfolder
    
    environment:
      groups:
        - ios_creds  # Create this group in Codemagic UI
      vars:
        XCODE_WORKSPACE: "WebViewGold.xcworkspace"  # ← CHANGE THIS
        XCODE_SCHEME: "WebViewGold"                 # ← CHANGE THIS  
        BUNDLE_ID: "com.growthclimb.httsafety"    # From your Play Store
        APP_STORE_APP_ID: 6757065561           # ← ADD if publishing to App Store
      xcode: 16.0
      cocoapods: default  # Remove if not using CocoaPods
    
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
    
    scripts:
      - name: Install CocoaPods (if using)
        script: |
          if [ -f Podfile ]; then
            pod install
          fi
      
      - name: Set up keychain
        script: keychain initialize
      
      - name: Fetch signing files (automatic)
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID $APP_STORE_APP_ID --type IOS_APP_STORE --create
      
      - name: Add certificates to keychain
        script: keychain add-certificates
      
      - name: Configure code signing
        script: xcode-project use-profiles
      
      - name: Increment build number (if App Store publishing)
        script: |
          if [ ! -z "$APP_STORE_APP_ID" ]; then
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
          fi
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/**/*
    
    publishing:
      email:
        recipients:
          - sweettwinkle698@gmail.com # ← CHANGE THIS
        notify:
          success: true
          failure: true